Header, check, pls
Amfiteatr42/G5-IceCream pull request #4
Opened 2022-08-27 14:37 UTC by Serj96

2022-08-27 15:59 UTC, Amfiteatr42 requested changes

2022-08-27 15:59 UTC, Amfiteatr42 commented on src/index.html
> +      <div class="conteiner">
изменить название класса на container

2022-08-27 15:59 UTC, Amfiteatr42 commented on src/index.html
> +    <sectio class="hero">
пропущена буква в теге

2022-08-27 15:59 UTC, Amfiteatr42 commented on src/index.html
> +    <sectio class="hero">
в закрывающем -тоже

2022-08-27 15:59 UTC, Amfiteatr42 commented on src/index.html
> +              <svg class="menu__icon" aria-label="перемикач мобмльного меню">
сделай ариа лейбл на англ

2022-08-27 15:59 UTC, Amfiteatr42 commented on src/index.html
> +          <nav class="menu__desctop">
по БЭМу классы с названием блока не могут идти сразу с элементом. у тебя получается, что блок меню, и сразу с элементом десктоп. предлагаю изменить класс этого нава на просто "menu"

2022-08-27 15:59 UTC, Amfiteatr42 commented on src/index.html
> +          <div class="menu__btn-list">
зачем этот див? на него нет ни стилей, ни позиционирования.

2022-08-27 15:59 UTC, Amfiteatr42 commented on src/index.html
> +            <ul class="menu__mobil-list">
букву Е потерял)
ну это так..

2022-08-27 15:59 UTC, Amfiteatr42 commented on src/index.html
> +          <a href="" class="hero__link-made">How it’s made?</a>
добавить якорные ссылки

2022-08-27 15:59 UTC, Amfiteatr42 commented on src/index.html
> +                <a class="menu__mobil-link" href="#">Contact</a>
добавить якорные ссылки

2022-08-28 15:57 UTC, closed without merging

2022-08-28 15:58 UTC, Serj96 commented
done